/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.ImageIcon;

/**
 *
 * @author Maximiliano
 */
public class Donante extends javax.swing.JFrame {

    BackEnd.Controlador App;
    BackEnd.Donante eleccion;
    ImageIcon icon;

    /**
     * Creates new form Donante
     *
     */
    public Donante() {
        initComponents();
    }

    public Donante(BackEnd.Controlador app) {
        initComponents();
        this.App = app;

    }

    public void ConfigurarFicha(BackEnd.Donante Seleccionado) {
        eleccion = Seleccionado;
        setTitle("Donante: " + eleccion.getNombre() + " " + eleccion.getApellido());
        NombreDonante.setText(Seleccionado.getNombre() + " " + Seleccionado.getApellido());
        TipoDeSangre.setText(Seleccionado.getTipoSangre());
        Telefono.setText(Seleccionado.getTelefono());
        jLabel1.setEnabled(App.puedeDonar(Seleccionado));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FichaDonante = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AgregarDonante1 = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        ONTV1 = new javax.swing.JLabel();
        NombreDonante = new javax.swing.JLabel();
        TipoDeSangre = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        cancelar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 610));
        setMinimumSize(new java.awt.Dimension(550, 610));
        setResizable(false);
        setSize(new java.awt.Dimension(550, 610));

        FichaDonante.setBackground(new java.awt.Color(255, 255, 255));
        FichaDonante.setMaximumSize(new java.awt.Dimension(550, 610));
        FichaDonante.setMinimumSize(new java.awt.Dimension(550, 610));
        FichaDonante.setPreferredSize(new java.awt.Dimension(550, 610));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/DonarTrue.png"))); // NOI18N
        jLabel1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/DonarFalse.png"))); // NOI18N
        jLabel1.setOpaque(true);

        AgregarDonante1.setBackground(new java.awt.Color(0, 74, 127));
        AgregarDonante1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgregarDonante1.setForeground(new java.awt.Color(255, 255, 255));
        AgregarDonante1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/botonModificar.png"))); // NOI18N
        AgregarDonante1.setText("MODIFICAR");
        AgregarDonante1.setToolTipText("Guardar los datos modificados");
        AgregarDonante1.setBorder(null);
        AgregarDonante1.setBorderPainted(false);
        AgregarDonante1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarDonante1.setFocusPainted(false);
        AgregarDonante1.setOpaque(false);
        AgregarDonante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDonante1ActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(0, 74, 127));
        cancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/botonEliminar.png"))); // NOI18N
        cancelar.setText("ELIMINAR");
        cancelar.setToolTipText("");
        cancelar.setBorder(null);
        cancelar.setBorderPainted(false);
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar.setFocusPainted(false);
        cancelar.setOpaque(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        ONTV1.setFont(new java.awt.Font("Monospaced", 3, 48)); // NOI18N
        ONTV1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ONTV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Untitled-1.png"))); // NOI18N

        NombreDonante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N

        TipoDeSangre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Sangre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N

        Telefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N

        cancelar1.setBackground(new java.awt.Color(0, 74, 127));
        cancelar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelar1.setForeground(new java.awt.Color(255, 255, 255));
        cancelar1.setText("SALIR");
        cancelar1.setToolTipText("");
        cancelar1.setBorder(null);
        cancelar1.setBorderPainted(false);
        cancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar1.setFocusPainted(false);
        cancelar1.setOpaque(false);
        cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FichaDonanteLayout = new javax.swing.GroupLayout(FichaDonante);
        FichaDonante.setLayout(FichaDonanteLayout);
        FichaDonanteLayout.setHorizontalGroup(
            FichaDonanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ONTV1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FichaDonanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FichaDonanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TipoDeSangre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NombreDonante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addGroup(FichaDonanteLayout.createSequentialGroup()
                        .addComponent(AgregarDonante1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        FichaDonanteLayout.setVerticalGroup(
            FichaDonanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FichaDonanteLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ONTV1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(NombreDonante, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TipoDeSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(FichaDonanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarDonante1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FichaDonante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FichaDonante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        App.eliminarDonante(eleccion.getCedula(), eleccion.getTipoSangre());
        this.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void AgregarDonante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDonante1ActionPerformed
        ModificarPanel ModFicha = new ModificarPanel(eleccion, App);
        ModFicha.setVisible(true);
    }//GEN-LAST:event_AgregarDonante1ActionPerformed

    private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Donante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarDonante1;
    private javax.swing.JPanel FichaDonante;
    private javax.swing.JLabel NombreDonante;
    private javax.swing.JLabel ONTV1;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel TipoDeSangre;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelar1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
