/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Maximiliano
 */
public class ModificarPanel extends javax.swing.JFrame {

    private BackEnd.Donante eleccion;
    private BackEnd.Controlador app;
    /**
     * Creates new form ModificarPanel
     */
    public ModificarPanel() {
        initComponents();
    }

    public ModificarPanel(BackEnd.Donante eleccion, BackEnd.Controlador app) {
        initComponents();
        this.eleccion = eleccion;
        this.app = app;
        Nombre.setText(eleccion.getNombre());
        Apellidos.setText(eleccion.getApellido());
        CedulaDonante.setText(Integer.toString(eleccion.getCedula()));
        Telefono.setText(eleccion.getTelefono());

        PesoDonante.setText(Integer.toString(eleccion.getPeso()));
        TienePiercing.setSelected(eleccion.getPircing());
        Modelo2.addElement("Amazonas");
        Modelo2.addElement("Anzoátegui");
        Modelo2.addElement("Apure");
        Modelo2.addElement("Aragua");
        Modelo2.addElement("Barinas");
        Modelo2.addElement("Bolívar");
        Modelo2.addElement("Carabobo");
        Modelo2.addElement("Cojedes");
        Modelo2.addElement("Delta Amacuro");
        Modelo2.addElement("Distrito Capital");
        Modelo2.addElement("Falcón");
        Modelo2.addElement("Guárico");
        Modelo2.addElement("Lara");
        Modelo2.addElement("Mérida");
        Modelo2.addElement("Miranda");
        Modelo2.addElement("Monagas");
        Modelo2.addElement("Nueva Esparta");
        Modelo2.addElement("Portuguesa");
        Modelo2.addElement("Sucre");
        Modelo2.addElement("Táchira");
        Modelo2.addElement("Trujillo");
        Modelo2.addElement("Vargas");
        Modelo2.addElement("Zulia");

        for (int i = 0; i < 23; i++) {
            if (Modelo2.getElementAt(i).equals(eleccion.getDireccion())) {
                Estados.setSelectedIndex(i);
                i = 23;//break
            }
        }

    }

    public int cuentaDigitos(String cadena) {
        int cant = 0;
        for (int i = 0; i < cadena.length(); i++) {
            if (Character.isDigit(cadena.charAt(i))) {
                cant++;
            }
        }
        return cant;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar = new javax.swing.JPanel();
        Nombre = new javax.swing.JTextField();
        Apellidos = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        TienePiercing = new javax.swing.JCheckBox();
        ModificarDonante = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        ONTV1 = new javax.swing.JLabel();
        FechaNacimiento = new com.toedter.calendar.JDateChooser();
        FechaUltDonacion = new com.toedter.calendar.JDateChooser();
        FechaUltPiercing = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        Masculino = new javax.swing.JRadioButton();
        Femenino = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        O1 = new javax.swing.JRadioButton();
        O0 = new javax.swing.JRadioButton();
        A1 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        CedulaDonante = new javax.swing.JTextField();
        PesoDonante = new javax.swing.JTextField();
        HeDonado = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        Modelo2 = new DefaultListModel();
        Estados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Agregar.setBackground(new java.awt.Color(255, 255, 255));
        Agregar.setMinimumSize(new java.awt.Dimension(530, 462));

        Nombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Nombre.setText(" ");
        Nombre.setToolTipText("Ej: Pepito Jose");
        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombres", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N

        Apellidos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Apellidos.setText(" ");
        Apellidos.setToolTipText("Ej: Perez Gonzalez");
        Apellidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellidos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N
        Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosActionPerformed(evt);
            }
        });

        Telefono.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Telefono.setText(" ");
        Telefono.setToolTipText("Ej: 04126958754");
        Telefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N

        TienePiercing.setBackground(new java.awt.Color(255, 255, 255));
        TienePiercing.setForeground(new java.awt.Color(0, 74, 127));
        TienePiercing.setText("Piercings o Tatuajes");
        TienePiercing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TienePiercingActionPerformed(evt);
            }
        });

        ModificarDonante.setBackground(new java.awt.Color(0, 74, 127));
        ModificarDonante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ModificarDonante.setForeground(new java.awt.Color(255, 255, 255));
        ModificarDonante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/botonModificar.png"))); // NOI18N
        ModificarDonante.setText("MODIFICAR");
        ModificarDonante.setToolTipText("Agregar un Donante");
        ModificarDonante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        ModificarDonante.setBorderPainted(false);
        ModificarDonante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarDonante.setFocusPainted(false);
        ModificarDonante.setOpaque(false);
        ModificarDonante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarDonanteActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(0, 74, 127));
        cancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/botonCancelar.png"))); // NOI18N
        cancelar.setText("CANCELAR");
        cancelar.setToolTipText("");
        cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cancelar.setBorderPainted(false);
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar.setFocusPainted(false);
        cancelar.setOpaque(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        ONTV1.setFont(new java.awt.Font("Monospaced", 3, 48)); // NOI18N
        ONTV1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ONTV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Untitled-1.png"))); // NOI18N

        FechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        FechaNacimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de nacimiento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N
        FechaNacimiento.setEnabled(false);

        FechaUltDonacion.setBackground(new java.awt.Color(255, 255, 255));
        FechaUltDonacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de última donación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N
        FechaUltDonacion.setEnabled(false);

        FechaUltPiercing.setBackground(new java.awt.Color(255, 255, 255));
        FechaUltPiercing.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de último piercing o tatuaje", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N
        FechaUltPiercing.setEnabled(TienePiercing.isSelected());
        FechaUltPiercing.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);

        Masculino.setText("Masculino");
        Masculino.setEnabled(false);

        Femenino.setText("Femenino");
        Femenino.setEnabled(false);
        Femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemeninoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Masculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(Femenino)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Masculino)
                    .addComponent(Femenino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Sangre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N
        jPanel2.setEnabled(false);

        O1.setText("O+");
        O1.setEnabled(false);

        O0.setText("O-");
        O0.setEnabled(false);

        A1.setText("A+");
        A1.setEnabled(false);

        jRadioButton6.setText("A-");
        jRadioButton6.setEnabled(false);

        jRadioButton7.setText("B+");
        jRadioButton7.setEnabled(false);

        jRadioButton8.setText("B-");
        jRadioButton8.setEnabled(false);

        jRadioButton9.setText("AB+");
        jRadioButton9.setEnabled(false);

        jRadioButton10.setText("AB-");
        jRadioButton10.setEnabled(false);

        jRadioButton11.setText("Rh+");
        jRadioButton11.setEnabled(false);

        jRadioButton12.setText("Rh-");
        jRadioButton12.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton8)
                    .addComponent(O1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(O0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(A1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton11)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(O1)
                    .addComponent(O0)
                    .addComponent(A1)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton12))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CedulaDonante.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        CedulaDonante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N
        CedulaDonante.setEnabled(false);

        PesoDonante.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PesoDonante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Peso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 74, 127))); // NOI18N

        HeDonado.setBackground(new java.awt.Color(255, 255, 255));
        HeDonado.setForeground(new java.awt.Color(0, 74, 127));
        HeDonado.setText("Nunca he donado sangre");
        HeDonado.setEnabled(false);
        HeDonado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeDonadoActionPerformed(evt);
            }
        });

        Estados.setModel(Modelo2);
        Estados.setForeground(new java.awt.Color(0, 74, 127));
        jScrollPane2.setViewportView(Estados);

        javax.swing.GroupLayout AgregarLayout = new javax.swing.GroupLayout(Agregar);
        Agregar.setLayout(AgregarLayout);
        AgregarLayout.setHorizontalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarLayout.createSequentialGroup()
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ModificarDonante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CedulaDonante)))
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(FechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PesoDonante)))
                        .addGap(10, 10, 10)
                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellidos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Telefono, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HeDonado)
                                    .addComponent(TienePiercing))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(FechaUltDonacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addComponent(FechaUltPiercing, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ONTV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        AgregarLayout.setVerticalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLayout.createSequentialGroup()
                .addComponent(ONTV1)
                .addGap(5, 5, 5)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(Apellidos))
                .addGap(5, 5, 5)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono)
                    .addComponent(CedulaDonante))
                .addGap(5, 5, 5)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addComponent(PesoDonante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addComponent(TienePiercing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HeDonado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FechaUltPiercing, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(FechaUltDonacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModificarDonante, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidosActionPerformed

    private void TienePiercingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TienePiercingActionPerformed
        FechaUltPiercing.setEnabled(TienePiercing.isSelected());
    }//GEN-LAST:event_TienePiercingActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void FemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemeninoActionPerformed

    private void HeDonadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeDonadoActionPerformed
        FechaUltDonacion.setEnabled(!HeDonado.isSelected());
    }//GEN-LAST:event_HeDonadoActionPerformed

    private void ModificarDonanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarDonanteActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "Seguro que deseas hacer estas modificaciones?", "Warning", dialogButton);
        boolean exito = true;
        String nombre = Nombre.getText();
        String apellido = Apellidos.getText();
        String tlfn = Telefono.getText();
        int Index = Estados.getSelectedIndex();
        String direccion = "";
        if (Index != -1) {
            direccion = (String) Modelo2.get(Index);
        }
        int peso = 0;
        if (PesoDonante.getText().length() == cuentaDigitos(PesoDonante.getText())) {
            peso = Integer.parseInt(PesoDonante.getText());
        } else {
            exito = false;
        }
        if (dialogButton == JOptionPane.YES_OPTION) {
            if (nombre.isEmpty() || cuentaDigitos(nombre) != 0) {
                JOptionPane.showMessageDialog(null, "Nombre no valido!");
                exito = false;
            } else if (apellido.isEmpty() || cuentaDigitos(apellido) != 0) {
                JOptionPane.showMessageDialog(null, "Apellido no valido!");
                exito = false;
            } else if (tlfn.isEmpty() || cuentaDigitos(tlfn) != 11 || tlfn.length() != cuentaDigitos(tlfn)) {
                JOptionPane.showMessageDialog(null, "Telefono no valido!");
                exito = false;
            } else if (direccion.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No puedes dejar la direccion vacia!");
                exito = false;
            } else if (peso < 1) {
                JOptionPane.showMessageDialog(null, "Error en el peso!");
                exito = false;
            } else if (TienePiercing.isSelected()) {
                if (FechaUltPiercing.getDate() == null) {
                    JOptionPane.showMessageDialog(null, "Seleccione la fecha de su ultimo piercing!");
                    exito = false;
                }
            }
            if (exito) {
                eleccion.setNombre(Nombre.getText());
                eleccion.setApellido(Apellidos.getText());
                eleccion.setTelefono(Telefono.getText());
                eleccion.setDireccion(direccion);
                eleccion.setPeso(Integer.parseInt(PesoDonante.getText()));
                if (TienePiercing.isSelected()) {
                    if (FechaUltPiercing.getDateFormatString().length() != 0) {
                        eleccion.setUltPircing(FechaUltPiercing.getDate());
                    }
                }else{
                    eleccion.setUltPircing(eleccion.getUltPircing());
                }
                this.dispose();
                app.escribirData();
            }
        }
    }//GEN-LAST:event_ModificarDonanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ModificarPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A1;
    private javax.swing.JPanel Agregar;
    private javax.swing.JTextField Apellidos;
    private javax.swing.JTextField CedulaDonante;
    private javax.swing.JList<String> Estados;
    private DefaultListModel Modelo2;
    private com.toedter.calendar.JDateChooser FechaNacimiento;
    private com.toedter.calendar.JDateChooser FechaUltDonacion;
    private com.toedter.calendar.JDateChooser FechaUltPiercing;
    private javax.swing.JRadioButton Femenino;
    private javax.swing.JCheckBox HeDonado;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.JButton ModificarDonante;
    private javax.swing.JTextField Nombre;
    private javax.swing.JRadioButton O0;
    private javax.swing.JRadioButton O1;
    private javax.swing.JLabel ONTV1;
    private javax.swing.JTextField PesoDonante;
    private javax.swing.JTextField Telefono;
    private javax.swing.JCheckBox TienePiercing;
    private javax.swing.JButton cancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
